name: CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  ci-cd:
    runs-on: self-hosted
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s-specifications

