name: Update README Progress

on:
  workflow_run:
    workflows: ["Microservices CI"] # Name of the CI workflow file (from `name:` in ci.yaml)
    types:
      - completed

jobs:
  update-tasks:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      startsWith(github.event.workflow_run.head_commit.message, 'task-done:')
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Update README
        run: |
          python - <<'EOF'
          import re
          import os

          commit_message = os.getenv("COMMIT_MSG", "")
          task_name = commit_message.split("task-done:", 1)[1].strip()

          readme_path = "README.md"
          with open(readme_path, "r", encoding="utf-8") as f:
              content = f.read()

          # Match unchecked task case-insensitively
          pattern = rf"- \[ \] {re.escape(task_name)}"
          updated_content = re.sub(
              pattern,
              f"- [x] {task_name}",
              content,
              flags=re.IGNORECASE
          )

          # Recalculate progress
          total_tasks = len(re.findall(r"- \[.\]", updated_content))
          done_tasks = len(re.findall(r"- \[x\]", updated_content))
          progress = int((done_tasks / total_tasks) * 100) if total_tasks else 0

          # Update progress bar
          updated_content = re.sub(
              r"!\[progress\]\(https://progress-bar.dev/\d+/?\)",
              f"![progress](https://progress-bar.dev/{progress}/)",
              updated_content
          )

          with open(readme_path, "w", encoding="utf-8") as f:
              f.write(updated_content)

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Auto-update task and progress bar" || echo "No changes to commit"
          git push
        env:
          COMMIT_MSG: ${{ github.event.workflow_run.head_commit.message }}

