name: Update README Progress

on:
  workflow_run:
    workflows: ["Microservices CI"]
    types:
      - completed

jobs:
  update-tasks:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      startsWith(github.event.workflow_run.head_commit.message, 'task-done:')
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Update README
        run: |
          python - <<'EOF'
          import re
          import os

          commit_message = os.getenv("COMMIT_MSG", "")
          if "task-done:" not in commit_message.lower():
              print("No task-done: in commit message. Skipping.")
              exit(0)

          task_name = commit_message.split("task-done:", 1)[1].strip()

          readme_path = "README.md"
          with open(readme_path, "r", encoding="utf-8") as f:
              content = f.read()

          already_done_pattern = rf"- \[x\] {re.escape(task_name)}"
          if re.search(already_done_pattern, content, flags=re.IGNORECASE):
              print(f"Task '{task_name}' is already marked done. Skipping update.")
              exit(0)

          pattern = rf"- \[ \] {re.escape(task_name)}"
          updated_content = re.sub(
              pattern,
              f"- [x] {task_name}",
              content,
              flags=re.IGNORECASE
          )

          with open(readme_path, "w", encoding="utf-8") as f:
              f.write(updated_content)

          print(f"Updated task '{task_name}' in README.")
          EOF
        env:
          COMMIT_MSG: ${{ github.event.workflow_run.head_commit.message }}

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Auto-update task" || echo "No changes to commit"
          git push

