name: Vote Service CI

on:
  push:
    branches:
      - main
    paths:
      - 'vote/**' # Trigger only when changes are in the 'vote' directory
      - '.github/workflows/vote-ci.yaml'
  pull_request:
    branches:
      - main
    paths:
      - 'vote/**'
      - '.github/workflows/vote-ci.yaml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' # Adjust to your Python version

      - name: Lint Vote Service (Flake8)
        run: |
          pip install flake8
          flake8 vote/app.py

     # - name: Run SCA on Vote Service (Trivy)
       # uses: aquasecurity/trivy-action@master
       # with:
         # scanners: "vuln"
         # format: "table"
         # target: "vote"
         # ignore-unfixed: true
         # severity: "HIGH,CRITICAL"

      - name: Run SAST on Vote Service (Bandit)
        run: |
          pip install bandit
          bandit -r vote/ -ll -f json -o bandit-results.json || true # Allow failure to view report

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Vote service image
        uses: docker/build-push-action@v5
        with:
          context: ./vote
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/vote-find-your-bias:${{ github.sha }}, ${{ secrets.DOCKER_HUB_USERNAME }}/vote-find-your-bias:latest
