name: Worker Service CI

on:
  push:
    branches:
      - main
    paths:
      - 'worker/**' # Trigger only when changes are in the 'worker' directory
      - '.github/workflows/worker-ci.yaml'
  pull_request:
    branches:
      - main
    paths:
      - 'worker/**'
      - '.github/workflows/worker-ci.yaml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0' # Adjust to your .NET version

      # No specific linting/SAST for C# shown in previous example, but you'd add tools like SonarQube Scanner or Roslyn Analyzers here.

      #- name: Run SCA on Worker Service (Trivy)
       # uses: aquasecurity/trivy-action@master
        #with:
         # scanners: "vuln"
          #format: "table"
          #target: "worker"
          #ignore-unfixed: true
          #severity: "HIGH,CRITICAL"

     # - name: Run Worker Service Unit Tests
       # run: |
         # cd worker
         # dotnet test Worker.csproj # Assumes unit tests are in the project

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Worker service image
        uses: docker/build-push-action@v5
        with:
          context: ./worker
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/worker-find-your-bias:${{ github.sha }}, ${{ secrets.DOCKER_HUB_USERNAME }}/worker-find-your-bias:latest
